import React from 'react';
import { Cpu, Zap, Shield, Globe, BookOpen, Terminal, ChevronRight, Server, Code, Network, Laptop, Lock, Anchor, Layers } from 'lucide-react';

const HowItWorksView: React.FC = () => {
  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-12"><div className="relative overflow-hidden rounded-2xl border border-trenchPurple-500/30 bg-whale-900 p-8 shadow-[0_0_50px_rgba(126,34,206,0.1)]"><div className="absolute top-0 right-0 p-8 opacity-5"><BookOpen size={200} /></div><h1 className="text-4xl font-black text-white tracking-tighter mb-4">HOW IT <span className="text-trenchPurple-500">WORKS</span></h1><p className="text-xl text-whale-text max-w-3xl font-light leading-relaxed">The bridge between your laptop and industrial-grade supremacy. We don't sell cloud subscriptions. We rent you raw, physical power and trader-grade routing.</p></div><div className="bg-whale-800 border border-trenchGold-500/20 rounded-xl p-8 relative overflow-hidden"><div className="absolute top-0 left-0 w-1 h-full bg-trenchGold-500"></div><div className="flex items-center gap-3 mb-6"><Network className="text-trenchGold-500" size={32} /><h2 className="text-3xl font-bold text-white tracking-tight">YOUR LAPTOP IS THE COCKPIT. <br/><span className="text-slate-500">THE RIG IS THE ENGINE.</span></h2></div><div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative z-10"><div className="bg-whale-900/50 p-6 rounded-xl border border-whale-700"><Laptop className="text-slate-300 mb-4" size={32} /><h3 className="text-lg font-bold text-white mb-2">1. The Interface</h3><p className="text-sm text-slate-400 leading-relaxed">Your MacBook or consumer laptop runs the lightweight dashboard. You keep full custody of your keys. No heavy lifting happens here. You are the pilot.</p></div><div className="hidden md:flex items-center justify-center text-trenchGold-500"><ChevronRight size={40} className="animate-pulse" /></div><div className="bg-whale-900/50 p-6 rounded-xl border border-whale-700"><Lock className="text-trenchPurple-500 mb-4" size={32} /><h3 className="text-lg font-bold text-white mb-2">2. The Tunnel</h3><p className="text-sm text-slate-400 leading-relaxed">We establish a <span className="text-trenchPurple-400 font-bold">Cloudflare Zero-Trust Tunnel</span> directly to the hardware.</p></div></div></div></div>
  );
};
export default HowItWorksView;
