import React, { useState, useEffect, useRef } from 'react';
import { Sparkles, Image as ImageIcon, Share2, Twitter, Copy, Zap, RefreshCw, Aperture, Skull, Smile, Download, Crown, Palette, TrendingUp, Wallet } from 'lucide-react';
import { generateMemeText, renderMemeToCanvas } from '../services/memeService';
import { WhaleLogoIcon } from './BrandAssets';
import { Position, WhaleTransaction } from '../types';

const PERSONALITIES = [
    { id: 'WHALEBOT', name: 'WhaleBot AI', icon: <Zap size={16} className="text-diamond-500"/>, color: 'border-diamond-500/30 text-diamond-400' },
    { id: 'PERPGOAT', name: 'PerpGoat', icon: <Skull size={16} className="text-rose-500"/>, color: 'border-rose-500/30 text-rose-400' },
    { id: 'TRUMP', name: 'DONALD PUMP', icon: <Crown size={16} className="text-trenchGold-500"/>, color: 'border-trenchGold-500/30 text-trenchGold-400 bg-trenchGold-500/10' },
    { id: 'PERPSHARK', name: 'PerpShark', icon: <Aperture size={16} className="text-blue-500"/>, color: 'border-blue-500/30 text-blue-400' },
    { id: 'PERPJEET', name: 'PerpJeet', icon: <Smile size={16} className="text-emerald-500"/>, color: 'border-emerald-500/30 text-emerald-400' },
];

// Pass in live data props
interface MemeReactorProps {
    positions?: Position[];
    whaleFeed?: WhaleTransaction[];
}

const MemeReactor: React.FC<MemeReactorProps> = ({ positions = [], whaleFeed = [] }) => {
    const [topic, setTopic] = useState('BTC PUMP');
    const [personality, setPersonality] = useState('WHALEBOT');
    const [isGenerating, setIsGenerating] = useState(false);
    const [feed, setFeed] = useState<Array<{id: string, text: string, author: string, timestamp: number}>>([]);
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const [currentText, setCurrentText] = useState<string | null>(null);

    // Auto-Generate Feed
    useEffect(() => {
        const interval = setInterval(async () => {
            if (Math.random() > 0.85) {
                const p = PERSONALITIES[Math.floor(Math.random() * PERSONALITIES.length)];
                const t = await generateMemeText('MARKET', p.id as any);
                setFeed(prev => [{ id: Date.now().toString(), text: t, author: p.name, timestamp: Date.now() }, ...prev.slice(0, 20)]);
            }
        }, 8000);
        return () => clearInterval(interval);
    }, []);

    const handleGenerate = async (customTopic?: string) => {
        setIsGenerating(true);
        const activeTopic = customTopic || topic;
        const text = await generateMemeText(activeTopic, personality as any);
        setCurrentText(text);
        setFeed(prev => [{ id: Date.now().toString(), text: text, author: PERSONALITIES.find(p => p.id === personality)?.name || 'AI', timestamp: Date.now() }, ...prev]);
        setIsGenerating(false);
    };

    // Quick Actions
    const memeMyPosition = () => {
        if (positions.length > 0) {
            const p = positions[0];
            handleGenerate(`MY ${p.leverage}x ${p.type} ON ${p.asset}`);
        } else {
            handleGenerate("NO POSITIONS (SAD)");
        }
    };

    const memeLatestWhale = () => {
        if (whaleFeed.length > 0) {
            const w = whaleFeed[0];
            handleGenerate(`WHALE ${w.action} ${w.asset}`);
        } else {
            handleGenerate("WHALES ARE SLEEPING");
        }
    };

    // Render Canvas when text changes
    useEffect(() => { if (currentText && canvasRef.current) renderMemeToCanvas(currentText, canvasRef.current); }, [currentText]);

    const handleDownload = () => {
        if (canvasRef.current) {
            const link = document.createElement('a');
            link.download = `whaleperp-meme-${Date.now()}.png`;
            link.href = canvasRef.current.toDataURL();
            link.click();
        }
    };

    const handleTwitterShare = () => {
        const tweetText = `Generated by @WhalePerp AI 🐳\n\n"${currentText}"\n\n#WhalePerp #Crypto #AI`;
        const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}`;
        window.open(url, '_blank');
    };

    return (
        <div className="max-w-7xl mx-auto animate-in fade-in slide-in-from-bottom-4 pb-12 grid grid-cols-1 lg:grid-cols-12 gap-8">
            
            {/* LEFT: GENERATOR CONSOLE (8 Cols) */}
            <div className="lg:col-span-8 space-y-8">
                <div className="bg-whale-800 border border-trenchGold-500/30 rounded-xl p-8 relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-8 opacity-5"><Sparkles size={150} /></div>
                    
                    <div className="flex justify-between items-center mb-8 relative z-10">
                        <div className="flex items-center gap-3">
                            <div className="p-2 bg-whale-900 rounded-lg border border-trenchGold-500/50 shadow-[0_0_15px_rgba(255,215,0,0.2)]">
                                <Sparkles className="text-trenchGold-500" size={24} />
                            </div>
                            <div>
                                <h1 className="text-3xl font-black text-white tracking-tight leading-none">MEME REACTOR</h1>
                                <p className="text-xs text-trenchPurple-400 font-mono tracking-widest">v1.3 // POSITION AWARE</p>
                            </div>
                        </div>
                        <div className="flex gap-2">
                            <button onClick={memeMyPosition} className="px-3 py-1.5 bg-emerald-500/10 border border-emerald-500/30 rounded hover:bg-emerald-500/20 text-emerald-400 text-xs font-bold flex items-center gap-2 transition-colors">
                                <TrendingUp size={14} /> MEME MY POSITION
                            </button>
                            <button onClick={memeLatestWhale} className="px-3 py-1.5 bg-blue-500/10 border border-blue-500/30 rounded hover:bg-blue-500/20 text-blue-400 text-xs font-bold flex items-center gap-2 transition-colors">
                                <Wallet size={14} /> MEME WHALE ALERT
                            </button>
                        </div>
                    </div>

                    <div className="space-y-6 relative z-10">
                        <div>
                            <label className="text-xs text-slate-500 uppercase tracking-wider mb-3 block font-bold flex items-center gap-2"><Palette size={12}/> Select Personality Engine</label>
                            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3">
                                {PERSONALITIES.map(p => (<button key={p.id} onClick={() => setPersonality(p.id)} className={`flex items-center justify-center gap-2 p-3 rounded-lg border transition-all ${personality === p.id ? `bg-whale-900 ${p.color} shadow-[0_0_15px_rgba(0,0,0,0.3)] ring-1 ring-white/10` : 'bg-whale-900/50 border-whale-700 text-slate-500 hover:text-slate-300'}`}>{p.icon} <span className="text-xs font-bold">{p.name}</span></button>))}
                            </div>
                        </div>
                        <div className="flex gap-2">
                            <input type="text" value={topic} onChange={e => setTopic(e.target.value)} className="flex-1 bg-whale-900 border border-whale-700 rounded-lg px-4 py-3 text-white focus:border-trenchGold-500 outline-none font-mono text-sm placeholder:text-slate-600" placeholder="Enter topic (e.g. ETH, TRUMP, JEETS)..." />
                            <button onClick={() => handleGenerate()} disabled={isGenerating} className="bg-trenchGold-500 hover:bg-trenchGold-400 text-whale-900 font-bold px-6 py-3 rounded-lg transition-transform active:scale-95 flex items-center gap-2 shadow-[0_0_20px_rgba(255,215,0,0.3)]">{isGenerating ? <RefreshCw className="animate-spin" size={20}/> : <Zap size={20} fill="currentColor"/>} MINT MEME</button>
                        </div>
                    </div>
                </div>

                {/* CANVAS PREVIEW */}
                <div className={`bg-whale-900 border border-whale-700 rounded-xl overflow-hidden shadow-2xl transition-all duration-500 ${currentText ? 'opacity-100 scale-100' : 'opacity-50 scale-95'}`}>
                    <div className="relative bg-black aspect-video flex items-center justify-center">
                        {!currentText && <p className="text-slate-600 font-mono text-xs animate-pulse">AWAITING INPUT DATA...</p>}
                        <canvas ref={canvasRef} width={800} height={450} className={`w-full h-full ${!currentText && 'hidden'}`} />
                    </div>
                    <div className="bg-whale-800 p-4 flex justify-between items-center border-t border-whale-700">
                        <div className="flex gap-2">
                            <button onClick={handleDownload} disabled={!currentText} className="p-2 bg-whale-700 hover:bg-whale-600 rounded text-slate-300 transition-colors flex items-center gap-2 text-xs font-bold px-4 border border-whale-600 disabled:opacity-50"><Download size={14}/> SAVE PNG</button>
                        </div>
                        <button onClick={handleTwitterShare} disabled={!currentText} className="flex items-center gap-2 bg-[#1DA1F2] hover:bg-[#1a91da] text-white px-5 py-2 rounded font-bold text-xs transition-transform active:scale-95 disabled:opacity-50 shadow-lg"><Twitter size={14} fill="currentColor"/> POST TO X</button>
                    </div>
                </div>
            </div>

            {/* RIGHT: LIVE FEED (4 Cols) */}
            <div className="lg:col-span-4 bg-whale-900 border border-whale-700 rounded-xl flex flex-col h-[600px]">
                <div className="p-4 border-b border-whale-800 bg-whale-800/50"><h3 className="font-bold text-white flex items-center gap-2"><ImageIcon size={18} className="text-trenchPurple-500"/> LIVE FEED</h3></div>
                <div className="flex-1 overflow-y-auto p-4 space-y-4 scrollbar-thin scrollbar-thumb-whale-700">
                    {feed.map(post => (
                        <div key={post.id} className="bg-whale-800 rounded-lg p-4 border border-whale-700 animate-in slide-in-from-right-4 duration-300 hover:border-trenchGold-500/30 transition-colors cursor-pointer group">
                            <div className="flex justify-between items-start mb-2">
                                <span className="text-xs font-bold text-trenchGold-500">{post.author}</span>
                                <span className="text-[10px] text-slate-600">{new Date(post.timestamp).toLocaleTimeString()}</span>
                            </div>
                            <p className="text-sm text-slate-300 italic leading-relaxed group-hover:text-white transition-colors">"{post.text}"</p>
                            <div className="mt-3 flex justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                <button onClick={() => { setTopic(post.text); handleGenerate(post.text); }} className="text-[10px] text-slate-400 hover:text-white bg-whale-900 px-2 py-1 rounded">REMIX</button>
                                <button className="text-slate-500 hover:text-white transition-colors"><Share2 size={14}/></button>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

        </div>
    );
};
export default MemeReactor;
