import React from 'react';
import { Lock, Server, Link, ShieldCheck, Cpu, CheckCircle, XCircle, AlertTriangle } from 'lucide-react';

const ProtocolView: React.FC = () => {
  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500"><div className="relative overflow-hidden rounded-2xl border border-trenchGold-500/30 bg-whale-900 p-8 text-center shadow-[0_0_50px_rgba(255,215,0,0.1)]"><div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-trenchGold-500 to-transparent"></div><h1 className="text-4xl md:text-5xl font-black text-white tracking-tighter mb-4">THIS IS <span className="text-trenchGold-500">NOT</span> A CASINO</h1><p className="text-xl text-whale-text max-w-2xl mx-auto font-light leading-relaxed">The first verifiable, local-node perpetual trading protocol running on <span className="text-diamond-500 font-mono">Real Hardware</span>.</p></div><div className="bg-whale-900/50 border border-whale-700 rounded-xl p-8 mt-12"><div className="grid grid-cols-1 md:grid-cols-2 gap-12"><div><h3 className="text-rose-400 font-bold tracking-widest text-sm border-b border-rose-900/50 pb-2">WHAT WE ARE NOT</h3><ul className="space-y-3"><li className="flex items-start gap-3 text-slate-400"><XCircle className="text-rose-500 shrink-0 mt-0.5" size={16} /><span className="text-sm">We are <strong>NOT</strong> an exchange.</span></li><li className="flex items-start gap-3 text-slate-400"><XCircle className="text-rose-500 shrink-0 mt-0.5" size={16} /><span className="text-sm">We do <strong>NOT</strong> custody funds or assets.</span></li><li className="flex items-start gap-3 text-slate-400"><XCircle className="text-rose-500 shrink-0 mt-0.5" size={16} /><span className="text-sm">We do <strong>NOT</strong> operate an orderbook.</span></li></ul></div><div className="space-y-4"><h3 className="text-emerald-400 font-bold tracking-widest text-sm border-b border-emerald-900/50 pb-2">WHAT WE ARE</h3><ul className="space-y-3"><li className="flex items-start gap-3 text-slate-300"><CheckCircle className="text-emerald-500 shrink-0 mt-0.5" size={16} /><span className="text-sm">Secure AI Intelligence Platform</span></li><li className="flex items-start gap-3 text-slate-300"><CheckCircle className="text-emerald-500 shrink-0 mt-0.5" size={16} /><span className="text-sm">High-Performance Compute Provider (IaaS)</span></li><li className="flex items-start gap-3 text-slate-300"><CheckCircle className="text-emerald-500 shrink-0 mt-0.5" size={16} /><span className="text-sm">Non-Custodial Interface for YOUR API Keys</span></li></ul></div></div></div></div>
  );
};
export default ProtocolView;
