import React, { useState } from 'react';
import { TrendingUp, TrendingDown, Zap, X, Wallet } from 'lucide-react';
interface TradeExecutionProps { currentPrice: number; selectedAsset: string; onPlaceOrder: (type: 'LONG' | 'SHORT', size: number, leverage: number) => void; }
const TradeExecution: React.FC<TradeExecutionProps> = ({ currentPrice, selectedAsset, onPlaceOrder }) => {
  const [size, setSize] = useState(5000); const [leverage, setLeverage] = useState(10); const [modal, setModal] = useState<'LONG'|'SHORT'|null>(null);
  return (
    <>
      <div className="bg-whale-800 border border-whale-700 rounded-xl p-6 shadow-lg"><div className="flex items-center gap-2 mb-6 border-b border-whale-700 pb-4"><Zap className="text-trenchGold-500" size={20} /><h3 className="font-bold text-white">Quick Execution</h3></div><div className="space-y-6"><div className="bg-whale-900/50 p-4 rounded text-center"><p className="text-2xl font-mono font-bold text-white">${currentPrice.toFixed(2)}</p></div><div className="grid grid-cols-2 gap-4"><button onClick={() => setModal('LONG')} className="flex flex-col items-center p-6 rounded-xl bg-gradient-to-br from-emerald-600 to-emerald-900 border border-emerald-500/50"><span className="flex items-center gap-2 font-black text-white text-xl">BUY <TrendingUp size={24}/></span></button><button onClick={() => setModal('SHORT')} className="flex flex-col items-center p-6 rounded-xl bg-gradient-to-br from-rose-600 to-rose-900 border border-rose-500/50"><span className="flex items-center gap-2 font-black text-white text-xl">SELL <TrendingDown size={24}/></span></button></div></div></div>
      {modal && (<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm"><div className="w-full max-w-md bg-whale-900 border border-whale-700 rounded-2xl p-6"><div className="flex justify-between items-center mb-6"><h3 className="text-xl font-bold text-white">Configure {modal}</h3><button onClick={() => setModal(null)}><X className="text-slate-400"/></button></div><div className="space-y-6"><div><label className="text-slate-400 text-sm">Size: ${size}</label><input type="range" min="1000" max="25000" step="1000" value={size} onChange={e=>setSize(Number(e.target.value))} className="w-full h-2 bg-whale-800 rounded-lg appearance-none"/></div><div><label className="text-slate-400 text-sm">Leverage: {leverage}x</label><input type="range" min="1" max="50" value={leverage} onChange={e=>setLeverage(Number(e.target.value))} className="w-full h-2 bg-whale-800 rounded-lg appearance-none"/></div><button onClick={() => { onPlaceOrder(modal, size, leverage); setModal(null); }} className={`w-full py-3 rounded-lg font-bold text-whale-900 ${modal === 'LONG' ? 'bg-emerald-500' : 'bg-rose-500'}`}>CONFIRM ORDER</button></div></div></div>)}
    </>
  );
};
export default TradeExecution;
